#!/usr/bin/env python3
"""
Decode a slice of an audio file (MP3 / WAV / M4A / ...) into a mono signed
PCM C array and write src/song_pcm.c.

Pipeline:
    input.mp3 --ffmpeg--> mono / target Fs / s16|s32 WAV --wave--> array --> .c

Prereq:
    sudo apt install -y ffmpeg

Examples (run from .../tas2505/):
    # 30 s starting at 0:45, 16 kHz mono (~937 KB - too big for xG27 flash!)
    python3 src/tools/gen_song_mp3.py tmp/SomeoneLikeYou.mp3 --start 45 --duration 30

    # 15 s @ 16 kHz, fits xG27 flash (~469 KB)
    python3 src/tools/gen_song_mp3.py tmp/SomeoneLikeYou.mp3 --start 70 --duration 15

    # 30 s @ 8 kHz, fits xG27 flash (~469 KB) - but build with -DFRAME_CLK_HZ=8000
    python3 src/tools/gen_song_mp3.py tmp/SomeoneLikeYou.mp3 --start 45 --duration 30 --fs 8000

    # 30 s @ 8 kHz, 32-bit slots - build with -DFRAME_CLK_HZ=8000 -DWORD_SIZE=32
    python3 src/tools/gen_song_mp3.py tmp/TuyetYeuThuong.mp3 --start 27 --duration 15 --fs 8000 --bits 32

IMPORTANT - sample rate must match FRAME_CLK_HZ and --bits must match WORD_SIZE.
"""

import argparse
import os
import shutil
import struct
import subprocess
import sys
import tempfile


def need_tool(name):
    if shutil.which(name) is None:
        sys.exit(f"error: '{name}' not found. Install it (sudo apt install -y {name}).")


def probe_duration(path):
    """Return total duration of input file in seconds (float), or None."""
    res = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", path],
        capture_output=True, text=True,
    )
    try:
        return float(res.stdout.strip())
    except (ValueError, AttributeError):
        return None


def extract_mono_pcm(in_path, out_raw, start_s, dur_s, fs, gain_db, bits):
    """Use ffmpeg to slice + downmix + resample to mono raw PCM (s16le/s32le).

    Raw PCM output avoids WAVE_FORMAT_EXTENSIBLE headers (0xFFFE) that the
    stdlib `wave` module cannot parse for 32-bit samples.
    """
    fmt = "s16le" if bits == 16 else "s32le"
    cmd = [
        "ffmpeg", "-y", "-loglevel", "error",
        "-ss", f"{start_s}",        # seek BEFORE -i is fast & frame-accurate enough for MP3
        "-i", in_path,
        "-t", f"{dur_s}",
        "-ac", "1",                 # mono (downmix L+R)
        "-ar", str(fs),             # resample
        "-f", fmt,                   # raw PCM container
    ]
    if gain_db != 0:
        cmd += ["-af", f"volume={gain_db}dB"]
    cmd.append(out_raw)
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        sys.stderr.write(res.stderr)
        sys.exit("error: ffmpeg failed")


def read_raw_mono(path, bits):
    """Read mono raw PCM; return list of signed ints."""
    bytes_per_sample = bits // 8
    with open(path, "rb") as f:
        raw = f.read()
    if len(raw) % bytes_per_sample != 0:
        sys.exit(f"error: raw size {len(raw)} not multiple of {bytes_per_sample}")
    n = len(raw) // bytes_per_sample
    code = "h" if bits == 16 else "i"
    return list(struct.unpack(f"<{n}{code}", raw))


HEADER = """\
/*
 * Auto-generated by src/tools/gen_song_mp3.py -- DO NOT EDIT BY HAND.
 *
 * Mono {bits}-bit signed PCM, sample rate {fs} Hz, {n} samples (~{dur:.2f} s).
 * Source: {src} (slice {start}s .. {end}s, gain {gain:+d} dB).
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "song_pcm.h"

const size_t   SONG_PCM_SAMPLE_NO = {n}U;

const {ctype} song_pcm[{n}] = {{
"""

FOOTER = "};\n"


def emit_c(samples, fs, src, start, end, gain, path, bits):
    n = len(samples)
    dur = n / fs
    ctype = "int16_t" if bits == 16 else "int32_t"
    width = 6 if bits == 16 else 11
    per_line = 12 if bits == 16 else 8
    with open(path, "w") as f:
        f.write(HEADER.format(bits=bits, fs=fs, n=n, dur=dur, ctype=ctype,
                              src=os.path.basename(src),
                              start=start, end=end, gain=gain))
        for i in range(0, n, per_line):
            chunk = samples[i:i + per_line]
            f.write("\t" + ", ".join(f"{s:{width}d}" for s in chunk) + ",\n")
        f.write(FOOTER)
    return n, dur


def main():
    p = argparse.ArgumentParser(description="MP3/WAV/M4A -> src/song_pcm.c")
    p.add_argument("input", help="path to input audio file (mp3, wav, m4a, ...)")
    p.add_argument("--start", type=float, default=0.0,
                   help="start offset in seconds (e.g. 45 for chorus). Default 0.")
    p.add_argument("--duration", type=float, default=15.0,
                   help="clip length in seconds. Default 15.")
    p.add_argument("--fs", type=int, default=16000,
                   help="target sample rate; MUST equal FRAME_CLK_HZ at build. Default 16000.")
    p.add_argument("--bits", type=int, default=16, choices=[16, 32],
                   help="PCM slot width; MUST equal WORD_SIZE at build. Default 16.")
    p.add_argument("--gain", type=int, default=0,
                   help="apply volume gain in dB (e.g. +6 to boost, -3 to attenuate). Default 0.")
    p.add_argument("-o", "--out",
                   default=os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                        "..", "song_pcm.c"))
    args = p.parse_args()

    if not os.path.isfile(args.input):
        sys.exit(f"error: input not found: {args.input}")

    need_tool("ffmpeg")
    need_tool("ffprobe")

    total = probe_duration(args.input)
    if total is not None:
        print(f"input: {args.input}  total ~{total:.2f} s")
        if args.start >= total:
            sys.exit(f"error: --start {args.start}s >= file length {total:.2f}s")
        if args.start + args.duration > total:
            new_dur = total - args.start
            print(f"WARN: clipping duration {args.duration}s -> {new_dur:.2f}s to fit file")
            args.duration = new_dur

    end = args.start + args.duration
    print(f"extracting {args.start:.2f}s .. {end:.2f}s, mono s{args.bits}, "
          f"fs={args.fs}, gain={args.gain:+d} dB")

    with tempfile.TemporaryDirectory() as td:
        raw = os.path.join(td, "clip.raw")
        extract_mono_pcm(args.input, raw, args.start, args.duration,
                         args.fs, args.gain, args.bits)
        samples = read_raw_mono(raw, args.bits)
        fs = args.fs

    out_path = os.path.abspath(args.out)
    n, dur = emit_c(samples, fs, args.input, args.start, end, args.gain,
                    out_path, args.bits)
    bytes_per_sample = args.bits // 8
    size_kb = (n * bytes_per_sample) / 1024.0
    print(f"wrote {out_path}")
    print(f"  fs={fs} Hz  bits={args.bits}  samples={n}  duration={dur:.2f}s  size={size_kb:.1f} KB")

    # xG27: ~768 KiB flash; app+Zephyr ~200 KiB -> keep PCM rodata <= ~500 KiB.
    flash_pcm_max_kb = 500
    if size_kb > flash_pcm_max_kb:
        max_dur = (flash_pcm_max_kb * 1024) / (fs * bytes_per_sample)
        print()
        print(f"ERROR: PCM array {size_kb:.1f} KB > {flash_pcm_max_kb} KB "
              f"(xG27 flash budget).")
        print(f"       At fs={fs} bits={args.bits}, use --duration <= ~{max_dur:.1f} s, "
              "or lower --fs, or build with -DAUDIO_SOURCE=short_songs.")
        sys.exit(1)
    print("Next steps:")
    print(f"  west build -p always -b xg27_dk2602a "
          f"zephyr-4.4.0/samples/drivers/i2s/tas2505 "
          f"-d build/tas2505_w{args.bits} -- -DFRAME_CLK_HZ={fs} -DWORD_SIZE={args.bits}")
    print(f"  west flash -d build/tas2505_w{args.bits}")


if __name__ == "__main__":
    main()
