/*
 * Declarations for the 1 kHz sine test vectors (one .c file per Fs).
 * Auto-generated by src/tools/gen_sine_pcm.py -- DO NOT EDIT BY HAND.
 *
 * Pure 1000 Hz sine.  Each Fs ships four arrays covering
 * the full SRS 1.f x 1.g matrix:
 *
 *   sine1khz_16bit_mono_pcm_<rate>     int16_t   SRS 1.f.i  + 1.g.i   (mandatory)
 *   sine1khz_32bit_mono_pcm_<rate>     int32_t   SRS 1.f.ii + 1.g.i   (optional)
 *   sine1khz_16bit_stereo_pcm_<rate>   int16_t   SRS 1.f.i  + 1.g.ii  (optional)
 *   sine1khz_32bit_stereo_pcm_<rate>   int32_t   SRS 1.f.ii + 1.g.ii  (optional)
 *
 * Stereo layout: [L0, R0, L1, R1, ...] with L == R (same 1 kHz tone).
 *
 * Every array is exactly N integer cycles long so the loop boundary is
 * glitch-free even at 44.1 kHz (where one period spans 44.1 samples).
 *
 *   Fs (Hz) | mono samples | mono bytes (s16/s32) | stereo bytes (s16/s32) | cycles
 *   --------+--------------+----------------------+------------------------+-------
 *      8000 |          800 |       1600 /    3200 |        3200 /    6400  |    100
 *     16000 |         1600 |       3200 /    6400 |        6400 /   12800  |    100
 *     44100 |         4410 |       8820 /   17640 |       17640 /   35280  |    100
 *     48000 |         4800 |       9600 /   19200 |       19200 /   38400  |    100
 *
 * All four arrays for a given Fs ship in the same sine_<rate>.c file;
 * the linker drops the three unused ones via --gc-sections.  audio_sine.c
 * selects the array at compile time from FRAME_CLK_HZ (file) + WORD_SIZE_BITS
 * (resolution) + CHANNEL_MODE_ID (mono vs stereo).
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef AUDIO_SINE_SINE_H_
#define AUDIO_SINE_SINE_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Fs = 8000 Hz */
extern const int16_t      sine1khz_16bit_mono_pcm_8k[];
extern const unsigned int sine1khz_16bit_mono_pcm_8k_len;
extern const int32_t      sine1khz_32bit_mono_pcm_8k[];
extern const unsigned int sine1khz_32bit_mono_pcm_8k_len;
extern const int16_t      sine1khz_16bit_stereo_pcm_8k[];   /* interleaved L,R,L,R, ... */
extern const unsigned int sine1khz_16bit_stereo_pcm_8k_len; /* total int16_t count (= 2 * frames) */
extern const int32_t      sine1khz_32bit_stereo_pcm_8k[];   /* interleaved L,R,L,R, ... */
extern const unsigned int sine1khz_32bit_stereo_pcm_8k_len; /* total int32_t count (= 2 * frames) */

/* Fs = 16000 Hz */
extern const int16_t      sine1khz_16bit_mono_pcm_16k[];
extern const unsigned int sine1khz_16bit_mono_pcm_16k_len;
extern const int32_t      sine1khz_32bit_mono_pcm_16k[];
extern const unsigned int sine1khz_32bit_mono_pcm_16k_len;
extern const int16_t      sine1khz_16bit_stereo_pcm_16k[];   /* interleaved L,R,L,R, ... */
extern const unsigned int sine1khz_16bit_stereo_pcm_16k_len; /* total int16_t count (= 2 * frames) */
extern const int32_t      sine1khz_32bit_stereo_pcm_16k[];   /* interleaved L,R,L,R, ... */
extern const unsigned int sine1khz_32bit_stereo_pcm_16k_len; /* total int32_t count (= 2 * frames) */

/* Fs = 44100 Hz */
extern const int16_t      sine1khz_16bit_mono_pcm_44k[];
extern const unsigned int sine1khz_16bit_mono_pcm_44k_len;
extern const int32_t      sine1khz_32bit_mono_pcm_44k[];
extern const unsigned int sine1khz_32bit_mono_pcm_44k_len;
extern const int16_t      sine1khz_16bit_stereo_pcm_44k[];   /* interleaved L,R,L,R, ... */
extern const unsigned int sine1khz_16bit_stereo_pcm_44k_len; /* total int16_t count (= 2 * frames) */
extern const int32_t      sine1khz_32bit_stereo_pcm_44k[];   /* interleaved L,R,L,R, ... */
extern const unsigned int sine1khz_32bit_stereo_pcm_44k_len; /* total int32_t count (= 2 * frames) */

/* Fs = 48000 Hz */
extern const int16_t      sine1khz_16bit_mono_pcm_48k[];
extern const unsigned int sine1khz_16bit_mono_pcm_48k_len;
extern const int32_t      sine1khz_32bit_mono_pcm_48k[];
extern const unsigned int sine1khz_32bit_mono_pcm_48k_len;
extern const int16_t      sine1khz_16bit_stereo_pcm_48k[];   /* interleaved L,R,L,R, ... */
extern const unsigned int sine1khz_16bit_stereo_pcm_48k_len; /* total int16_t count (= 2 * frames) */
extern const int32_t      sine1khz_32bit_stereo_pcm_48k[];   /* interleaved L,R,L,R, ... */
extern const unsigned int sine1khz_32bit_stereo_pcm_48k_len; /* total int32_t count (= 2 * frames) */

#ifdef __cplusplus
}
#endif

#endif /* AUDIO_SINE_SINE_H_ */
